### ISSUE TITLE
Incorrect seed display for Minecraft 1.1 maps.

### ISSUE THREAD

**Issue by lig** [iversc/Minecraft-Save-Seed-Reader#2]
On newly generated maps using Minecraft 1.1 I'm always getting the same incorrect seed for every different map.

**Comment by iversc** [comment]
Are you sure you're picking your world from the drop-down list?  My world displays the correct seed, generating 3 new worlds in 1.1 all yielded correct results, and making my own seed gave the correct result.  Can you tell me what the seed is in Minecraft, and what my program is saying?  (Press F3 to show the seed in Minecraft while in a world.  A screenshot of both will work)

**Comment by iversc** [comment]
Also, are you getting any error messages, and can you open up all your worlds properly in Minecraft?

**Comment by lig** [comment]
Just checked again. Everything works fine. Sorry!

I think that this was because of errors with old maps that were broken long time ago. I should remove them anyway.

Thank you!
